ALTER TABLE "SlotWeight"
ADD COLUMN "w_working_day" DOUBLE PRECISION NOT NULL DEFAULT 0.2;

ALTER TABLE "SlotWeight"
ALTER COLUMN "w_time" SET DEFAULT 0.3;

ALTER TABLE "SlotWeight"
ALTER COLUMN "w_compact" SET DEFAULT 0.3;

ALTER TABLE "SlotWeight"
ALTER COLUMN "w_priority" SET DEFAULT 0.2;
