ALTER TABLE "Client" ADD COLUMN "address" TEXT;

ALTER TABLE "SlotWeight"
ADD COLUMN "desired_break_minutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "w_travel" DOUBLE PRECISION NOT NULL DEFAULT 0.15;
